In [2]:
#Exercício 1 – Seleção avançada e filtros 
#Utilizando o DataFrame lido do ficheiro exercício_vendas.csv
import pandas as pd 
import numpy as np 
df_vendas = pd.read_csv("exercicio_vendas.csv")
display(df_vendas)

print("_________________________________________________________")
#a) Filtra todas as linhas em que a categoria é “Eletrónica” ou em que a quantidade vendida seja superior a 5
#df_vendas.query( Eletrónica' and 'Quantidade' > 5")

df_filtrado= df_vendas [(df_vendas['Categoria']== 'Eletrónica') & (df_vendas['Quantidade'] > 5 )]
display(df_filtrado)
print("__________________________________________________________")
#b) Mostra apenas as colunas “Produto”, “Categoria” e “Quantidade” dessas linhas filtradas

df_filtrado = df_filtrado[['Produto', 'Categoria', 'Quantidade']]
display(df_filtrado)

         Produto   Categoria  Quantidade    Preço        Data
0      Telemóvel  Eletrónica         5.0   350.00  2025-01-12
1       Portátil  Eletrónica         3.0  1200.50  2025-02-15
2        T-shirt   Vestuário        10.0    15.99  2025-01-20
3         Calças   Vestuário         7.0    34.50  2025-03-01
4        Sapatos   Vestuário         4.0    50.00  2025-02-10
5        Relógio  Acessórios         6.0   120.00  2025-01-25
6        Mochila  Acessórios         NaN    45.00  2025-02-05
7         Chapéu  Acessórios        15.0    12.99  2025-03-12
8        Monitor  Eletrónica         2.0   220.00  2025-02-20
9        Teclado  Eletrónica         6.0    80.00  2025-03-14
10        Blusão   Vestuário         5.0      NaN  2025-03-18
11          Bota   Vestuário         3.0    75.00  2025-04-02
12  Porta-moedas  Acessórios        12.0    25.00  2025-03-22
13    Auiculares  Eletrónica        10.0   150.00  2025-04-05
14      Camisola   Vestuário         7.0    30.50  2025-04-10
15      Camisola   Vestuário         7.0    30.50  2025-04-10

_________________________________________________________

       Produto   Categoria  Quantidade  Preço        Data
9      Teclado  Eletrónica         6.0   80.0  2025-03-14
13  Auiculares  Eletrónica        10.0  150.0  2025-04-05

__________________________________________________________

       Produto   Categoria  Quantidade
9      Teclado  Eletrónica         6.0
13  Auiculares  Eletrónica        10.0

In [3]:
#Exercício 2 – Tratamento de dados ausentes e duplicados 
#1. Conta, para cada coluna, quantos valores ausentes (NaN) existem no DataFrame original. 

qt_nulos= df_vendas.isna().sum()
print (qt_nulos)
print("________________________________________________________________")
#2. Preenche todos os valores ausentes na coluna “Preço” com a média dessa mesma coluna. 

media_preco= df_vendas['Preço'].mean()
print(media_preco)

df_vendas['Preço']=df_vendas['Preço'].fillna(media_preco)
display(df_vendas)
print("____________________________________________________________")

qt_media= df_vendas['Quantidade'].mean()
print(qt_media)
df_vendas['Quantidade']= df_vendas['Quantidade'].fillna(qt_media).astype(int)
display(df_vendas)
print("____________________________________________________________")


#3. Remove eventuais linhas duplicadas e mostra o novo DataFrame. 
df_vendas = df_vendas.drop_duplicates()
display(df_vendas)

Produto       0
Categoria     0
Quantidade    1
Preço         1
Data          0
dtype: int64
________________________________________________________________
162.66533333333334

         Produto   Categoria  Quantidade        Preço        Data
0      Telemóvel  Eletrónica         5.0   350.000000  2025-01-12
1       Portátil  Eletrónica         3.0  1200.500000  2025-02-15
2        T-shirt   Vestuário        10.0    15.990000  2025-01-20
3         Calças   Vestuário         7.0    34.500000  2025-03-01
4        Sapatos   Vestuário         4.0    50.000000  2025-02-10
5        Relógio  Acessórios         6.0   120.000000  2025-01-25
6        Mochila  Acessórios         NaN    45.000000  2025-02-05
7         Chapéu  Acessórios        15.0    12.990000  2025-03-12
8        Monitor  Eletrónica         2.0   220.000000  2025-02-20
9        Teclado  Eletrónica         6.0    80.000000  2025-03-14
10        Blusão   Vestuário         5.0   162.665333  2025-03-18
11          Bota   Vestuário         3.0    75.000000  2025-04-02
12  Porta-moedas  Acessórios        12.0    25.000000  2025-03-22
13    Auiculares  Eletrónica        10.0   150.000000  2025-04-05
14      Camisola   Vestuário         7.0    30.500000  2025-04-10
15      Camisola   Vestuário         7.0    30.500000  2025-04-10

____________________________________________________________
6.8

         Produto   Categoria  Quantidade        Preço        Data
0      Telemóvel  Eletrónica           5   350.000000  2025-01-12
1       Portátil  Eletrónica           3  1200.500000  2025-02-15
2        T-shirt   Vestuário          10    15.990000  2025-01-20
3         Calças   Vestuário           7    34.500000  2025-03-01
4        Sapatos   Vestuário           4    50.000000  2025-02-10
5        Relógio  Acessórios           6   120.000000  2025-01-25
6        Mochila  Acessórios           6    45.000000  2025-02-05
7         Chapéu  Acessórios          15    12.990000  2025-03-12
8        Monitor  Eletrónica           2   220.000000  2025-02-20
9        Teclado  Eletrónica           6    80.000000  2025-03-14
10        Blusão   Vestuário           5   162.665333  2025-03-18
11          Bota   Vestuário           3    75.000000  2025-04-02
12  Porta-moedas  Acessórios          12    25.000000  2025-03-22
13    Auiculares  Eletrónica          10   150.000000  2025-04-05
14      Camisola   Vestuário           7    30.500000  2025-04-10
15      Camisola   Vestuário           7    30.500000  2025-04-10

____________________________________________________________

         Produto   Categoria  Quantidade        Preço        Data
0      Telemóvel  Eletrónica           5   350.000000  2025-01-12
1       Portátil  Eletrónica           3  1200.500000  2025-02-15
2        T-shirt   Vestuário          10    15.990000  2025-01-20
3         Calças   Vestuário           7    34.500000  2025-03-01
4        Sapatos   Vestuário           4    50.000000  2025-02-10
5        Relógio  Acessórios           6   120.000000  2025-01-25
6        Mochila  Acessórios           6    45.000000  2025-02-05
7         Chapéu  Acessórios          15    12.990000  2025-03-12
8        Monitor  Eletrónica           2   220.000000  2025-02-20
9        Teclado  Eletrónica           6    80.000000  2025-03-14
10        Blusão   Vestuário           5   162.665333  2025-03-18
11          Bota   Vestuário           3    75.000000  2025-04-02
12  Porta-moedas  Acessórios          12    25.000000  2025-03-22
13    Auiculares  Eletrónica          10   150.000000  2025-04-05
14      Camisola   Vestuário           7    30.500000  2025-04-10

In [4]:
#Exercício 3 – Alteração de tipos de dados 
#1. Confere o tipo de dados da coluna “Quantidade”. 
df_vendas.info()
print(df_vendas['Quantidade'].dtypes)
print("___________________________________________________________________")

#2. Converte essa coluna para o tipo inteiro, se ainda não estiver. 

df_vendas['Quantidade']  = df_vendas['Quantidade'].astype(int)
display(df_vendas)
#3. Verifica novamente o tipo após a conversão.

<class 'pandas.core.frame.DataFrame'>
Index: 15 entries, 0 to 14
Data columns (total 5 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   Produto     15 non-null     object
 1   Categoria   15 non-null     object
 2   Quantidade  15 non-null     int64
 3   Preço       15 non-null     float64
 4   Data        15 non-null     object
dtypes: float64(1), int64(1), object(3)
memory usage: 720.0+ bytes
int64
___________________________________________________________________

         Produto   Categoria  Quantidade        Preço        Data
0      Telemóvel  Eletrónica           5   350.000000  2025-01-12
1       Portátil  Eletrónica           3  1200.500000  2025-02-15
2        T-shirt   Vestuário          10    15.990000  2025-01-20
3         Calças   Vestuário           7    34.500000  2025-03-01
4        Sapatos   Vestuário           4    50.000000  2025-02-10
5        Relógio  Acessórios           6   120.000000  2025-01-25
6        Mochila  Acessórios           6    45.000000  2025-02-05
7         Chapéu  Acessórios          15    12.990000  2025-03-12
8        Monitor  Eletrónica           2   220.000000  2025-02-20
9        Teclado  Eletrónica           6    80.000000  2025-03-14
10        Blusão   Vestuário           5   162.665333  2025-03-18
11          Bota   Vestuário           3    75.000000  2025-04-02
12  Porta-moedas  Acessórios          12    25.000000  2025-03-22
13    Auiculares  Eletrónica          10   150.000000  2025-04-05
14      Camisola   Vestuário           7    30.500000  2025-04-10

In [5]:
#Exercício 4 – Análise integrada de vendas (exercício mais extenso e completo) 
#Realiza a seguinte análise, utilizando e combinando os métodos .loc[], .isna(), .fillna(), .drop_duplicates(), .astype(), 
#.groupby():

#4.1. Lê o ficheiro CSV e apresenta as primeiras 5 linhas. 
df_vendas_orig=pd.read_csv('exercicio_vendas_orig.csv')
display(df_vendas_orig)

display(df_vendas.head())

print("_________________________________________________________________________________________")

         Produto   Categoria  Quantidade   Preço        Data
0      Telemóvel  Eletrónica         5.0     NaN  2025-01-12
1       Portátil  Eletrónica         3.0     NaN  2025-02-15
2        T-shirt   Vestuário        10.0   15.99  2025-01-20
3         Calças   Vestuário         7.0   34.50  2025-03-01
4        Sapatos   Vestuário         4.0     NaN  2025-02-10
5        Relógio  Acessórios         6.0  120.00  2025-01-25
6        Mochila  Acessórios         8.0   45.00  2025-02-05
7         Chapéu  Acessórios        15.0     NaN  2025-03-12
8        Monitor  Eletrónica         2.0  220.00  2025-02-20
9        Teclado  Eletrónica         NaN   80.00  2025-03-14
10        Blusão   Vestuário         5.0   40.00  2025-03-18
11          Bota   Vestuário         3.0   75.00  2025-04-02
12  Porta-moedas  Acessórios        12.0   25.00  2025-03-22
13    Auiculares  Eletrónica        10.0  150.00  2025-04-05
14    Auiculares  Eletrónica        10.0  150.00  2025-04-05
15    Auiculares  Eletrónica        10.0     NaN  2025-04-05
16      Camisola   Vestuário         7.0   30.50  2025-04-10

     Produto   Categoria  Quantidade    Preço        Data
0  Telemóvel  Eletrónica           5   350.00  2025-01-12
1   Portátil  Eletrónica           3  1200.50  2025-02-15
2    T-shirt   Vestuário          10    15.99  2025-01-20
3     Calças   Vestuário           7    34.50  2025-03-01
4    Sapatos   Vestuário           4    50.00  2025-02-10

_________________________________________________________________________________________

In [6]:
#4.2. Conta os valores ausentes por coluna e preenche todos os ausentes na coluna “Quantidade” com a moda dessa 
#coluna e os ausentes da coluna «Preço» com a média dessa coluna.. 


valores_ausentes = df_vendas_orig.isna().sum()
print("Quantidade de valores ausentes")

print(valores_ausentes)
print("_________________________________________________________________________________________")

quant_media= df_vendas_orig['Quantidade'].mode()[0] # para retomar o primeiro valor da moda 
print(f" A quantidade média é {quant_media}")

df_vendas_orig["Quantidade"]=df_vendas_orig["Quantidade"].fillna(media_preco).astype(int)
display(df_vendas_orig)

print("_________________________________________________________________________________________")

preco_media=df_vendas_orig['Preço'].mean()
print(f" A média do preço é {media_preco}")

df_vendas_orig["Preço"]=df_vendas_orig["Preço"].fillna(media_preco).astype(float)
print(df_vendas_orig)

Quantidade de valores ausentes
Produto       0
Categoria     0
Quantidade    1
Preço         5
Data          0
dtype: int64
_________________________________________________________________________________________
 A quantidade média é 10.0

         Produto   Categoria  Quantidade   Preço        Data
0      Telemóvel  Eletrónica           5     NaN  2025-01-12
1       Portátil  Eletrónica           3     NaN  2025-02-15
2        T-shirt   Vestuário          10   15.99  2025-01-20
3         Calças   Vestuário           7   34.50  2025-03-01
4        Sapatos   Vestuário           4     NaN  2025-02-10
5        Relógio  Acessórios           6  120.00  2025-01-25
6        Mochila  Acessórios           8   45.00  2025-02-05
7         Chapéu  Acessórios          15     NaN  2025-03-12
8        Monitor  Eletrónica           2  220.00  2025-02-20
9        Teclado  Eletrónica         162   80.00  2025-03-14
10        Blusão   Vestuário           5   40.00  2025-03-18
11          Bota   Vestuário           3   75.00  2025-04-02
12  Porta-moedas  Acessórios          12   25.00  2025-03-22
13    Auiculares  Eletrónica          10  150.00  2025-04-05
14    Auiculares  Eletrónica          10  150.00  2025-04-05
15    Auiculares  Eletrónica          10     NaN  2025-04-05
16      Camisola   Vestuário           7   30.50  2025-04-10

_________________________________________________________________________________________
 A média do preço é 162.66533333333334
         Produto   Categoria  Quantidade       Preço        Data
0      Telemóvel  Eletrónica           5  162.665333  2025-01-12
1       Portátil  Eletrónica           3  162.665333  2025-02-15
2        T-shirt   Vestuário          10   15.990000  2025-01-20
3         Calças   Vestuário           7   34.500000  2025-03-01
4        Sapatos   Vestuário           4  162.665333  2025-02-10
5        Relógio  Acessórios           6  120.000000  2025-01-25
6        Mochila  Acessórios           8   45.000000  2025-02-05
7         Chapéu  Acessórios          15  162.665333  2025-03-12
8        Monitor  Eletrónica           2  220.000000  2025-02-20
9        Teclado  Eletrónica         162   80.000000  2025-03-14
10        Blusão   Vestuário           5   40.000000  2025-03-18
11          Bota   Vestuário           3   75.000000  2025-04-02
12  Porta-moedas  Acessórios          12   25.000000  2025-03-22
13    Auiculares  Eletrónica          10  150.000000  2025-04-05
14    Auiculares  Eletrónica          10  150.000000  2025-04-05
15    Auiculares  Eletrónica          10  162.665333  2025-04-05
16      Camisola   Vestuário           7   30.500000  2025-04-10

In [7]:
##4.3.  Remove as linhas duplicadas

df_vendas_orig_sem_dup = df_vendas_orig.drop_duplicates() ##  a linha é removida, deixando de ter sequência,
display(df_vendas_orig_sem_dup)

         Produto   Categoria  Quantidade       Preço        Data
0      Telemóvel  Eletrónica           5  162.665333  2025-01-12
1       Portátil  Eletrónica           3  162.665333  2025-02-15
2        T-shirt   Vestuário          10   15.990000  2025-01-20
3         Calças   Vestuário           7   34.500000  2025-03-01
4        Sapatos   Vestuário           4  162.665333  2025-02-10
5        Relógio  Acessórios           6  120.000000  2025-01-25
6        Mochila  Acessórios           8   45.000000  2025-02-05
7         Chapéu  Acessórios          15  162.665333  2025-03-12
8        Monitor  Eletrónica           2  220.000000  2025-02-20
9        Teclado  Eletrónica         162   80.000000  2025-03-14
10        Blusão   Vestuário           5   40.000000  2025-03-18
11          Bota   Vestuário           3   75.000000  2025-04-02
12  Porta-moedas  Acessórios          12   25.000000  2025-03-22
13    Auiculares  Eletrónica          10  150.000000  2025-04-05
15    Auiculares  Eletrónica          10  162.665333  2025-04-05
16      Camisola   Vestuário           7   30.500000  2025-04-10

In [8]:
##4.4.Cria uma nova coluna “Valor_Total” que é o produto de “Quantidade” e “Preço”##


df_vendas_orig_sem_dup['Valor Total']=df_vendas_orig_sem_dup ['Quantidade'] * df_vendas_orig_sem_dup['Preço']
display(df_vendas_orig_sem_dup)

C:\Users\Neide Varela\AppData\Local\Temp\ipykernel_6028\1128770668.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df_vendas_orig_sem_dup['Valor Total']=df_vendas_orig_sem_dup ['Quantidade'] * df_vendas_orig_sem_dup['Preço']

         Produto   Categoria  Quantidade       Preço        Data   Valor Total
0      Telemóvel  Eletrónica           5  162.665333  2025-01-12    813.326667
1       Portátil  Eletrónica           3  162.665333  2025-02-15    487.996000
2        T-shirt   Vestuário          10   15.990000  2025-01-20    159.900000
3         Calças   Vestuário           7   34.500000  2025-03-01    241.500000
4        Sapatos   Vestuário           4  162.665333  2025-02-10    650.661333
5        Relógio  Acessórios           6  120.000000  2025-01-25    720.000000
6        Mochila  Acessórios           8   45.000000  2025-02-05    360.000000
7         Chapéu  Acessórios          15  162.665333  2025-03-12   2439.980000
8        Monitor  Eletrónica           2  220.000000  2025-02-20    440.000000
9        Teclado  Eletrónica         162   80.000000  2025-03-14  12960.000000
10        Blusão   Vestuário           5   40.000000  2025-03-18    200.000000
11          Bota   Vestuário           3   75.000000  2025-04-02    225.000000
12  Porta-moedas  Acessórios          12   25.000000  2025-03-22    300.000000
13    Auiculares  Eletrónica          10  150.000000  2025-04-05   1500.000000
15    Auiculares  Eletrónica          10  162.665333  2025-04-05   1626.653333
16      Camisola   Vestuário           7   30.500000  2025-04-10    213.500000

In [9]:
##4.5.Confirma que a coluna “Valor_Total” está no tipo float.
df_vendas_orig_sem_dup.info()

print("________________________________________________")
print(df_vendas_orig_sem_dup['Valor Total'].dtype)

<class 'pandas.core.frame.DataFrame'>
Index: 16 entries, 0 to 16
Data columns (total 6 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   Produto      16 non-null     object
 1   Categoria    16 non-null     object
 2   Quantidade   16 non-null     int64
 3   Preço        16 non-null     float64
 4   Data         16 non-null     object
 5   Valor Total  16 non-null     float64
dtypes: float64(2), int64(1), object(3)
memory usage: 896.0+ bytes
________________________________________________
float64

In [10]:
## 4.6 Agrupa o DataFrame por “Categoria” e mostra:
# O número total de produtos vendidos por cada categoria (soma das quantidades)
# O valor total vendido por categoria (soma dos “Valor_Total”)

agrupar_ctg = df_vendas_orig_sem_dup.groupby('Categoria').agg(
    Produtos_vend=('Quantidade', 'sum'),
    valor_total_vend=('Valor Total', 'sum')
).reset_index()
display(agrupar_ctg)

    Categoria  Produtos_vend  valor_total_vend
0  Acessórios             41       3819.980000
1  Eletrónica            192      17827.976000
2   Vestuário             36       1690.561333

In [11]:
# 4.7
# Ordena o resultado final por valor total vendido, do maior para o menor.

Resultado_final= agrupar_ctg.sort_values(by= 'valor_total_vend', ascending=False)
display(Resultado_final)

    Categoria  Produtos_vend  valor_total_vend
1  Eletrónica            192      17827.976000
0  Acessórios             41       3819.980000
2   Vestuário             36       1690.561333