In [ ]:
### Parte 1 -  Importação e Inspeção

In [5]:
## 1) Importe as bibliotecas necessárias. 

import pandas as pd
import numpy as np 
## 2) Carregue o ficheiro PL07_dados.csv (fornecido com este enunciado) para um DataFrame. 

df_dd_salarios = pd.read_csv("PL07_dados.csv")

print("___________________________________________________")

## 3) Mostre: 
   ## a) As 10 primeiras linhas do DataFrame. 
   
display(df_dd_salarios.head(10))
print("___________________________________________________")

   ## b) Informações gerais. 
display(df_dd_salarios.info())

print("___________________________________________________")

   ## c) Estatísticas descritivas (com 2 casas decimais). 
   
pd.options.display.float_format = '{:.2f}'.format

display(df_dd_salarios.describe())

___________________________________________________

             Nome  Idade Departamento   Salario
0     Ana Martins     28    Marketing   2425.70
1     Bruno Silva     29           TI   2637.22
2     Carla Gomes     56           RH   2294.45
3     Diogo Costa     35   Financeiro       NaN
4   Eduarda Rocha     38       Vendas   2231.80
5    Filipe Sousa     57       Vendas   2084.39
6  Gabriela Pinto     25       Vendas  12000.00
7    Hugo Almeida     23           TI   6000.00
8    Inês Moreira     27   Financeiro   2113.99
9    João Ribeiro     25           RH   1780.62

___________________________________________________
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 42 entries, 0 to 41
Data columns (total 4 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Nome          42 non-null     object
 1   Idade         42 non-null     int64
 2   Departamento  41 non-null     object
 3   Salario       38 non-null     float64
dtypes: float64(1), int64(1), object(2)
memory usage: 1.4+ KB

None

___________________________________________________

       Idade  Salario
count  42.00    38.00
mean   38.79  3297.90
std    10.30  3036.45
min    22.00  1284.45
25%    29.25  1909.68
50%    38.00  2239.27
75%    46.00  2474.47
max    57.00 15000.00

## Parte 2 — Seleção e Filtragem

In [6]:
## 1) Mostre apenas as colunas Nome e Idade. 

nome_idade=df_dd_salarios[['Nome','Idade']]
display(nome_idade)
print('____________________________________________________________')


## 2) Liste os registos com Idade > 30. 
nome_idade=df_dd_salarios.loc[df_dd_salarios ['Idade'] > 30,['Nome','Idade']]
display(nome_idade)

print('____________________________________________________________')

## 3) Selecione as linhas de índice 2 a 6, apenas das colunas Nome e Salario. 


nome_salario =df_dd_salarios.loc[2:6, ['Nome', 'Salario']]
display(nome_salario)

print('____________________________________________________________')

## 4) Filtre os registos com Departamento = 'Vendas' e Salario > 2000. 

filtrar = df_dd_salarios.loc[(df_dd_salarios['Departamento'] == 'Vendas') & (df_dd_salarios['Salario'] > 2000), ['Departamento', 'Salario', 'Nome']]
display(filtrar)

                Nome  Idade
0        Ana Martins     28
1        Bruno Silva     29
2        Carla Gomes     56
3        Diogo Costa     35
4      Eduarda Rocha     38
5       Filipe Sousa     57
6     Gabriela Pinto     25
7       Hugo Almeida     23
8       Inês Moreira     27
9       João Ribeiro     25
10  Liliana Teixeira     50
11     Miguel Araújo     39
12   Nádia Fernandes     47
13      Óscar Vieira     55
14    Patrícia Lopes     31
15     Rafael Santos     57
16      Sandra Neves     35
17    Tiago Carvalho     52
18      Vera Correia     36
19      Xavier Matos     29
20      Yara Marques     35
21          Zé Pedro     44
22        Maria Inês     42
23   Luís Figueiredo     37
24    Beatriz Castro     39
25     Ricardo Nunes     45
26       Sofia Pires     47
27       Pedro Matos     46
28     Carolina Lima     50
29       André Rocha     36
30     Marta Azevedo     22
31   Gonçalo Tavares     46
32       Helena Cruz     28
33       Rita Soares     30
34     Paulo Fonseca     45
35     Diana Ribeiro     22
36      Nelson Costa     29
37       Joana Lopes     45
38     Artur Freitas     32
39      Sérgio Cunha     38
40    Tiago Carvalho     52
41       Joana Lopes     45

____________________________________________________________

                Nome  Idade
2        Carla Gomes     56
3        Diogo Costa     35
4      Eduarda Rocha     38
5       Filipe Sousa     57
10  Liliana Teixeira     50
11     Miguel Araújo     39
12   Nádia Fernandes     47
13      Óscar Vieira     55
14    Patrícia Lopes     31
15     Rafael Santos     57
16      Sandra Neves     35
17    Tiago Carvalho     52
18      Vera Correia     36
20      Yara Marques     35
21          Zé Pedro     44
22        Maria Inês     42
23   Luís Figueiredo     37
24    Beatriz Castro     39
25     Ricardo Nunes     45
26       Sofia Pires     47
27       Pedro Matos     46
28     Carolina Lima     50
29       André Rocha     36
31   Gonçalo Tavares     46
34     Paulo Fonseca     45
37       Joana Lopes     45
38     Artur Freitas     32
39      Sérgio Cunha     38
40    Tiago Carvalho     52
41       Joana Lopes     45

____________________________________________________________

             Nome  Salario
2     Carla Gomes  2294.45
3     Diogo Costa      NaN
4   Eduarda Rocha  2231.80
5    Filipe Sousa  2084.39
6  Gabriela Pinto 12000.00

____________________________________________________________

   Departamento  Salario              Nome
4        Vendas  2231.80     Eduarda Rocha
5        Vendas  2084.39      Filipe Sousa
6        Vendas 12000.00    Gabriela Pinto
10       Vendas  2424.26  Liliana Teixeira
13       Vendas  8500.00      Óscar Vieira
19       Vendas  2116.51      Xavier Matos
26       Vendas  2104.18       Sofia Pires
29       Vendas  9000.00       André Rocha
31       Vendas  2212.83   Gonçalo Tavares
32       Vendas  2246.74       Helena Cruz

## Parte 3 — Limpeza e Tratamento de Dados  - Trabalhe numa cópia do DataFrame original.

In [ ]:
##1) Crie uma cópia do seu dataframe para limpar e tratar essa cópia, mantendo o dataframe original. Chame-lhe 
##df_tratado. 
df_tratado=pd.DataFrame(df_dd_salarios)
display(df_tratado)
print("_______________________________________________________________________")
## 2) Conte o número de valores ausentes (NaN) por coluna.  
conta_nulos = df_tratado.isna().sum()
display(conta_nulos)
print("_______________________________________________________________________")

##) 3) Para a coluna Salario em df_tratado, calcule, antes de qualquer substituição: 
##• Média  
##• Mediana 
valor_media= df_tratado['Salario'].mean()
print(f"A média do salário é :{valor_media}")

valor_mediana= df_tratado['Salario'].median()
print(f" O valor da médiana é : {valor_mediana}")
print("_______________________________________________________________________")

#  4) Decida qual das duas medidas (média ou mediana) é mais representativa para este conjunto de dados e 
## justifique a tua decisão 
coluna = 'Salario'
s1 =df_tratado[coluna]


## A mediana é usada porque representa o valor central dos dados, sendo menos influenciada por valores extremos que podem distorcer a média.

## 5) Substitua os NaN de Salario em df_tratado pela medida escolhida no ponto anterior.

df_tratado['Salario']=df_tratado['Salario'].fillna(valor_mediana)
display(df_tratado)
## 6) Elimine linhas duplicadas (se existirem) em df_tratado. 

df_tratado.duplicated()

df_tratado[df_tratado.duplicated()]

print("_______________________________________________________________________")

## 6) Elimine linhas duplicadas (se existirem) em df_tratado. 
df_tratado = df_tratado.drop_duplicates()
display(df_tratado)

print("_______________________________________________________________________")

## 7) Converta a coluna Idade para tipo inteiro adequado. 
print(df_tratado['Idade'].dtype)

                Nome  Idade Departamento  Salario
0        Ana Martins     28    Marketing  2425.70
1        Bruno Silva     29           TI  2637.22
2        Carla Gomes     56           RH  2294.45
3        Diogo Costa     35   Financeiro      NaN
4      Eduarda Rocha     38       Vendas  2231.80
5       Filipe Sousa     57       Vendas  2084.39
6     Gabriela Pinto     25       Vendas 12000.00
7       Hugo Almeida     23           TI  6000.00
8       Inês Moreira     27   Financeiro  2113.99
9       João Ribeiro     25           RH  1780.62
10  Liliana Teixeira     50       Vendas  2424.26
11     Miguel Araújo     39           TI  7000.00
12   Nádia Fernandes     47           RH 15000.00
13      Óscar Vieira     55       Vendas  8500.00
14    Patrícia Lopes     31       Vendas  1284.45
15     Rafael Santos     57          NaN  2374.32
16      Sandra Neves     35    Marketing  1773.18
17    Tiago Carvalho     52   Financeiro  2474.47
18      Vera Correia     36    Marketing  1884.79
19      Xavier Matos     29       Vendas  2116.51
20      Yara Marques     35   Financeiro  1716.75
21          Zé Pedro     44       Vendas      NaN
22        Maria Inês     42       Vendas  1979.06
23   Luís Figueiredo     37    Marketing  2436.41
24    Beatriz Castro     39    Marketing  2728.00
25     Ricardo Nunes     45           RH  2253.24
26       Sofia Pires     47       Vendas  2104.18
27       Pedro Matos     46   Financeiro  1840.16
28     Carolina Lima     50   Financeiro  1703.49
29       André Rocha     36       Vendas  9000.00
30     Marta Azevedo     22   Financeiro      NaN
31   Gonçalo Tavares     46       Vendas  2212.83
32       Helena Cruz     28       Vendas  2246.74
33       Rita Soares     30           TI  2526.32
34     Paulo Fonseca     45           TI  1886.56
35     Diana Ribeiro     22           RH  2362.42
36      Nelson Costa     29    Marketing  2063.16
37       Joana Lopes     45       Vendas  1665.63
38     Artur Freitas     32   Financeiro  2054.83
39      Sérgio Cunha     38    Marketing      NaN
40    Tiago Carvalho     52   Financeiro  2474.47
41       Joana Lopes     45       Vendas  1665.63

_______________________________________________________________________

Nome            0
Idade           0
Departamento    1
Salario         4
dtype: int64

_______________________________________________________________________
A média do salário é :3297.8955263157895
 O valor da médiana é : 2239.27
_______________________________________________________________________
 O desvio padrão é : (np.float64(3036.4538698626347), 2)

                Nome  Idade Departamento  Salario
0        Ana Martins     28    Marketing  2425.70
1        Bruno Silva     29           TI  2637.22
2        Carla Gomes     56           RH  2294.45
3        Diogo Costa     35   Financeiro  2239.27
4      Eduarda Rocha     38       Vendas  2231.80
5       Filipe Sousa     57       Vendas  2084.39
6     Gabriela Pinto     25       Vendas 12000.00
7       Hugo Almeida     23           TI  6000.00
8       Inês Moreira     27   Financeiro  2113.99
9       João Ribeiro     25           RH  1780.62
10  Liliana Teixeira     50       Vendas  2424.26
11     Miguel Araújo     39           TI  7000.00
12   Nádia Fernandes     47           RH 15000.00
13      Óscar Vieira     55       Vendas  8500.00
14    Patrícia Lopes     31       Vendas  1284.45
15     Rafael Santos     57          NaN  2374.32
16      Sandra Neves     35    Marketing  1773.18
17    Tiago Carvalho     52   Financeiro  2474.47
18      Vera Correia     36    Marketing  1884.79
19      Xavier Matos     29       Vendas  2116.51
20      Yara Marques     35   Financeiro  1716.75
21          Zé Pedro     44       Vendas  2239.27
22        Maria Inês     42       Vendas  1979.06
23   Luís Figueiredo     37    Marketing  2436.41
24    Beatriz Castro     39    Marketing  2728.00
25     Ricardo Nunes     45           RH  2253.24
26       Sofia Pires     47       Vendas  2104.18
27       Pedro Matos     46   Financeiro  1840.16
28     Carolina Lima     50   Financeiro  1703.49
29       André Rocha     36       Vendas  9000.00
30     Marta Azevedo     22   Financeiro  2239.27
31   Gonçalo Tavares     46       Vendas  2212.83
32       Helena Cruz     28       Vendas  2246.74
33       Rita Soares     30           TI  2526.32
34     Paulo Fonseca     45           TI  1886.56
35     Diana Ribeiro     22           RH  2362.42
36      Nelson Costa     29    Marketing  2063.16
37       Joana Lopes     45       Vendas  1665.63
38     Artur Freitas     32   Financeiro  2054.83
39      Sérgio Cunha     38    Marketing  2239.27
40    Tiago Carvalho     52   Financeiro  2474.47
41       Joana Lopes     45       Vendas  1665.63

_______________________________________________________________________

                Nome  Idade Departamento  Salario
0        Ana Martins     28    Marketing  2425.70
1        Bruno Silva     29           TI  2637.22
2        Carla Gomes     56           RH  2294.45
3        Diogo Costa     35   Financeiro  2239.27
4      Eduarda Rocha     38       Vendas  2231.80
5       Filipe Sousa     57       Vendas  2084.39
6     Gabriela Pinto     25       Vendas 12000.00
7       Hugo Almeida     23           TI  6000.00
8       Inês Moreira     27   Financeiro  2113.99
9       João Ribeiro     25           RH  1780.62
10  Liliana Teixeira     50       Vendas  2424.26
11     Miguel Araújo     39           TI  7000.00
12   Nádia Fernandes     47           RH 15000.00
13      Óscar Vieira     55       Vendas  8500.00
14    Patrícia Lopes     31       Vendas  1284.45
15     Rafael Santos     57          NaN  2374.32
16      Sandra Neves     35    Marketing  1773.18
17    Tiago Carvalho     52   Financeiro  2474.47
18      Vera Correia     36    Marketing  1884.79
19      Xavier Matos     29       Vendas  2116.51
20      Yara Marques     35   Financeiro  1716.75
21          Zé Pedro     44       Vendas  2239.27
22        Maria Inês     42       Vendas  1979.06
23   Luís Figueiredo     37    Marketing  2436.41
24    Beatriz Castro     39    Marketing  2728.00
25     Ricardo Nunes     45           RH  2253.24
26       Sofia Pires     47       Vendas  2104.18
27       Pedro Matos     46   Financeiro  1840.16
28     Carolina Lima     50   Financeiro  1703.49
29       André Rocha     36       Vendas  9000.00
30     Marta Azevedo     22   Financeiro  2239.27
31   Gonçalo Tavares     46       Vendas  2212.83
32       Helena Cruz     28       Vendas  2246.74
33       Rita Soares     30           TI  2526.32
34     Paulo Fonseca     45           TI  1886.56
35     Diana Ribeiro     22           RH  2362.42
36      Nelson Costa     29    Marketing  2063.16
37       Joana Lopes     45       Vendas  1665.63
38     Artur Freitas     32   Financeiro  2054.83
39      Sérgio Cunha     38    Marketing  2239.27

_______________________________________________________________________
int64

## Parte 4 — Estatística Descritiva - Utilize o dataframe limpo e tratado na Parte 3.

In [ ]:
##) Calcule, para a coluna Salario: 
# Média, Mediana, Moda, Quartis (Q1, Q2, Q3), Desvio Padrão (amostra), Coeficiente de Variação. 

salario_media = round(df_tratado['Salario'].mean(), 2)
print(f"O salário médio é: {salario_media}")
print("______________________________________________________")

salario_mediana= round(df_tratado['Salario'].median(), 2)
print(f" A mediana do salário é : {salario_mediana}")
print("______________________________________________________")

salario_moda =df_tratado['Salario'].mode()[0]
print(f" A moda  da variável salário é : {salario_moda}")

quartis = round(df_tratado['Salario'].quantile([0.25, 0.5, 0.75]), 2)
Q1 = quartis[0.25]
Q2 = quartis[0.5]
Q3 = quartis[0.75]
print(f"Q1: {Q1}")
print(f"Q2 (Mediana): {Q2}")
print(f"Q3: {Q3}")

print("______________________________________________________")

desvio_padrao = round(df_tratado['Salario'].std(ddof=1), 2 )
print(desvio_padrao)

print("______________________________________________________")


media = df_tratado['Salario'].mean()
coef_var = (desvio_padrao / media)*100%
print(coef_var)

O salário médio é: 3253.43
______________________________________________________
 A mediana do salário é : 2239.27
______________________________________________________
 A moda  da variável salário é : 2239.27
Q1: 2035.89
Q2 (Mediana): 2239.27
Q3: 2445.92
______________________________________________________
2962.17
______________________________________________________
91.04773499867562

##  Parte 5 — Agrupamento e Agregação - Utilize o dataframe limpo e tratado na Parte 3.

In [ ]:
##   1) Agrupe os dados por Departamento e apresente: 
# salário médio 
#Idade máxima
resultado_df_tratado = df_tratado.groupby('Departamento').agg({
    'Salario': 'mean',
    'Idade': 'max'
}).reset_index()

display(resultado_df_tratado)

print("__________________________________________")

tab_dinamica= df_tratado.pivot_table(values='Salario', index='Departamento', aggfunc='sum')
display(tab_dinamica)

  Departamento  Salario  Idade
0   Financeiro  2047.78     52
1    Marketing  2221.50     39
2           RH  4738.15     56
3           TI  4010.02     45
4       Vendas  3720.65     57

__________________________________________

              Salario
Departamento
Financeiro   16382.23
Marketing    15550.51
RH           23690.73
TI           20050.10
Vendas       52089.12